//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	internal class AboutBoxChessRefregitz : Form
	{
		public virtual string AssemblyTitle
		{
			get;
			private set;
		}

		public virtual string AssemblyVersion
		{
			get;
			private set;
		}

		public virtual string AssemblyDescription
		{
			get;
			private set;
		}

		public virtual string AssemblyProduct
		{
			get;
			private set;
		}

		public virtual string AssemblyCopyright
		{
			get;
			private set;
		}

		public virtual string AssemblyCompany
		{
			get;
			private set;
		}

		private IContainer components;

		private TableLayoutPanel tableLayoutPanel;

		private PictureBox logoPictureBox;

		private Label labelProductName;

		private Label labelVersion;

		private Label labelCopyright;

		private Label labelCompanyName;

		private TextBox textBoxDescription;

		private Button okButton;

		private void tableLayoutPanel_Paint(Object sender, PaintEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void labelCopyright_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void labelCompanyName_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void labelVersion_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void logoPictureBox_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		public AboutBoxChessRefregitz()
		{
		}

	}
}

