//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	internal class ChessGeneticAlgorithm
	{
		public bool BridgesKing;

		public int CromosomColumn;

		public int CromosomColumnFirst;

		public int CromosomRow;

		public int CromosomRowFirst;

		private int Gen1;

		private int Gen2;

		private IEnumerable<int> GeneticTable;

		private int Ki;

		public static bool NoGameFounf;

		private List<int> RowColumn;

		public ChessGeneticAlgorithm()
		{
		}

		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool FindGenToModified(IEnumerable<int> Cromosom1, IEnumerable<int> Cromosom2, List<int> List, int Index, int Order, bool and)
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<int> GenerateTable(List<int> List, int Index, int Order)
		{
			throw new System.NotImplementedException();
		}

	}
}

