//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ClassLoad
	{
		public ClassLoad()
		{
		}

		public static void Load_f()
		{
			throw new System.NotImplementedException();
		}

	}
}

