//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Drawing;
	using System.Linq;
	using System.Text;

	public class DrawSoldier : ThingsConverter
	{
		public Color color;

		public int Current;

		public int Order;

		public IEnumerable<int> Table;

		public Single ColumnS;

		public static Double MaxHuristicxS;

		public Single RowS;

		public IEnumerable<ThinkingChess> SoldierThinking;

		public virtual bool MaxFound(ref bool MaxNotFound)
		{
			throw new System.NotImplementedException();
		}

		public DrawSoldier(Single i, Single j, Color a, IEnumerable<int> Tab, int Ord, bool TB, int Cur, ref FormRefrigtz THIS)
		{
		}

		public DrawSoldier()
		{
		}

		public virtual Double ReturnHuristic()
		{
			throw new System.NotImplementedException();
		}

		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Clone(ref DrawSoldier AA, ref FormRefrigtz THIS)
		{
			throw new System.NotImplementedException();
		}

		public virtual void DrawSoldierOnTable(ref Graphics g, int CellW, int CellH)
		{
			throw new System.NotImplementedException();
		}

	}
}

