//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Drawing;
	using System.Linq;
	using System.Text;

	public class DrawElefant
	{
		public Color color;

		public Single Column;

		public int Current;

		public int Order;

		public Single Row;

		public IEnumerable<int> Table;

		public IEnumerable<ThinkingChess> ElefantThinking;

		public static Double MaxHuristicxE;

		public virtual bool MaxFound(ref bool MaxNotFound)
		{
			throw new System.NotImplementedException();
		}

		public DrawElefant(Single i, Single j, Color a, IEnumerable<int> Tab, int Ord, bool TB, int Cur, ref FormRefrigtz THIS)
		{
		}

		public DrawElefant()
		{
		}

		public virtual Double ReturnHuristic()
		{
			throw new System.NotImplementedException();
		}

		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Clone(ref DrawElefant AA, ref FormRefrigtz THIS)
		{
			throw new System.NotImplementedException();
		}

		public virtual void DrawElefantOnTable(ref Graphics g, int CellW, int CellH)
		{
			throw new System.NotImplementedException();
		}

	}
}

