//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormKindOfGameContinue : Form
	{
		private IContainer components;

		public ComboBox comboBoxDatabase;

		public RadioButton radioButtonBlitz;

		public RadioButton radioButtonComputerByComputer;

		public RadioButton radioButtonComputerByPerson;

		public RadioButton radioButtonGeneticGame;

		public FormKindOfGameContinue()
		{
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void FormKindOfGameContinue_Load(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void comboBoxDataBase_SelectedIndexChanged(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void radioButtonComputerByComputer_CheckedChanged(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

	}
}

