//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormُSelectItems : Form
	{
		private IContainer components;

		public static int Items;

		private PictureBox pictureBox1;

		private PictureBox pictureBox2;

		private PictureBox pictureBox3;

		private PictureBox pictureBox4;

		public FormُSelectItems()
		{
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void FormُSelectItems_Load(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void pictureBox1_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void pictureBox2_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void pictureBox3_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void pictureBox4_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

	}
}

