//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormSelect : Form
	{
		private IContainer components;

		private PictureBox pictureBoxBrown;

		private PictureBox pictureBoxGray;

		public RadioButton radioButtonBrownOrder;

		public RadioButton radioButtonGrayOrder;

		public FormSelect()
		{
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		private void FormSelect_Load(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public virtual void SetCloseVisible()
		{
			throw new System.NotImplementedException();
		}

	}
}

