//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Windows.Forms;

	public class FormTXT : Form
	{
		private IContainer components;

		private TextBox textBoxTXT;

		public FormTXT()
		{
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private void FormTXT_Load(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void textBox1_TextChanged(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

	}
}

