//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Text;
	using System.Threading;
	using System.Windows.Forms;

	public class Load : Form
	{
		private IContainer components;

		public static Load THIS;

		private bool exit;

		private ProgressBar progressBar1;

		private Thread t;

		private Thread tt;

		public Load()
		{
		}

		private void InitializeComponent()
		{
			throw new System.NotImplementedException();
		}

		protected virtual void Dispose(bool disposing)
		{
			throw new System.NotImplementedException();
		}

		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		private void Load_Load(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void progressBar1_Click(Object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		private void BaseThread()
		{
			throw new System.NotImplementedException();
		}

		private void LoadThread()
		{
			throw new System.NotImplementedException();
		}

		public virtual void SetCloseVisible()
		{
			throw new System.NotImplementedException();
		}

		public virtual void SetLoadVisible()
		{
			throw new System.NotImplementedException();
		}

	}
}

