//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	internal static class Program
	{
		public static Int64 SomeExtremelyLargeNumber
		{
			get;
			set;
		}

		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		public static void IncreasingThreadPerformance()
		{
			throw new System.NotImplementedException();
		}

		public static void Main()
		{
			throw new System.NotImplementedException();
		}

	}
}

