//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Globalization;
	using System.Linq;
	using System.Resources;
	using System.Text;

	internal class Resource1
	{
		internal static ResourceManager ResourceManager
		{
			internal get;
			private set;
		}

		internal static CultureInfo Culture
		{
			internal get;
			internal set;
		}

		private static ResourceManager resourceMan;

		private static CultureInfo resourceCulture;

		internal Resource1()
		{
		}

	}
}

