//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class RunRef
	{
		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		public virtual void RunRefregitz()
		{
			throw new System.NotImplementedException();
		}

		public RunRef()
		{
		}

	}
}

