//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class StackOverflowDetector
	{
		private static void CheckStackDepth()
		{
			throw new System.NotImplementedException();
		}

		public static int Recur()
		{
			throw new System.NotImplementedException();
		}

		public StackOverflowDetector()
		{
		}

	}
}

