//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading;

	internal class Syncronization
	{
		private bool LastState;

		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		public Syncronization(Thread t, int a)
		{
		}

		private bool Event(Thread t)
		{
			throw new System.NotImplementedException();
		}

		private bool Mutex(Thread t)
		{
			throw new System.NotImplementedException();
		}

		private bool Semaphore(Thread t)
		{
			throw new System.NotImplementedException();
		}

	}
}

