//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Drawing;
	using System.Linq;
	using System.Text;

	public class ThingsConverter
	{
		private Color color;

		public int Column;

		private int Current;

		private int Order;

		public int Row;

		public static bool ActOfClickEqualTow;

		public bool Convert;

		public bool ConvertedToBridge;

		public bool ConvertedToElefant;

		public bool ConvertedToHourse;

		public bool ConvertedToMinister;

		public int Max;

		public ThingsConverter()
		{
		}

		public ThingsConverter(int i, int j, Color a, IEnumerable<int> Tab, int Ord, bool TB, int Cur)
		{
		}

		public virtual bool ConvertOperation(int i, int j, Color a, IEnumerable<int> Tab, int Ord, bool TB, int Cur)
		{
			throw new System.NotImplementedException();
		}

	}
}

