//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Refrigtz
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading;

	public class Timer
	{
		public virtual Int64 TimesAccess
		{
			get;
			set;
		}

		public virtual Int64 TimesConstAccess
		{
			get;
			set;
		}

		public static bool AStarGreadyFirstSearch;

		public static Int64 AStarGreedytiLevelMax;

		public static bool UseDoubleTime;

		public static int StoreAllDrawCount;

		public int Sign;

		public Int64 Times;

		public bool Paused;

		public bool TextChanged;

		public bool EndTime;

		private Int64 ConstTimer;

		private Double AStarGreedytMidleTimer;

		private Int64 AStarGreedytLastTime;

		public static bool Text;

		private Int64 TimesBegin;

		private Thread t;

		private bool Infinity;

		public virtual string ReturnTime()
		{
			throw new System.NotImplementedException();
		}

		public Timer(bool SignPositive)
		{
		}

		public virtual void TimerInitiate()
		{
			throw new System.NotImplementedException();
		}

		public virtual void StartTime()
		{
			throw new System.NotImplementedException();
		}

		public virtual void StopTime()
		{
			throw new System.NotImplementedException();
		}

		private static void Log(Exception ex)
		{
			throw new System.NotImplementedException();
		}

		private void timerThread()
		{
			throw new System.NotImplementedException();
		}

		public virtual int AStarGreedytiLevelMaxInitiate(Timer TimerColor, int AStarGreedyti)
		{
			throw new System.NotImplementedException();
		}

		public virtual void SetAStarGreedytTimer()
		{
			throw new System.NotImplementedException();
		}

		public virtual void MidleAStarGreedytTimer(int AStarGreedyti)
		{
			throw new System.NotImplementedException();
		}

	}
}

