#pragma once

#include <string>

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace All
{
	namespace Properties
	{


		/// <summary>
		///   A strongly-typed resource class, for looking up localized strings, etc.
		/// </summary>
		// This class was auto-generated by the StronglyTypedResourceBuilder
		// class via a tool like ResGen or Visual Studio.
		// To add or remove a member, edit your .ResX file then rerun ResGen
		// with the /str option, or rebuild your VS project.
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")][System.Diagnostics.DebuggerNonUserCodeAttribute()][System.Runtime.CompilerServices.CompilerGeneratedAttribute()] internal class Resources
		class Resources
		{

		private:
			static System::Resources::ResourceManager *resourceMan;

			static System::Globalization::CultureInfo *resourceCulture;

		public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] internal Resources()
			Resources();

			/// <summary>
			///   Returns the cached ResourceManager instance used by this class.
			/// </summary>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] internal static System.Resources.ResourceManager ResourceManager
			static System::Resources::ResourceManager *getResourceManager() const;

			/// <summary>
			///   Overrides the current thread's CurrentUICulture property for all
			///   resource lookups using this strongly typed resource class.
			/// </summary>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//ORIGINAL LINE: [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] internal static System.Globalization.CultureInfo Culture
			static System::Globalization::CultureInfo *getCulture() const;
			static void setCulture(System::Globalization::CultureInfo *value);

			/// <summary>
			///   Looks up a localized string similar to public App()
			///{
			///    AppDomain.CurrentDomain.AssemblyResolve +=new ResolveEventHandler(CurrentDomain_AssemblyResolve);
			///}
			///
			///System.Reflection.Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
			///{
			///    string dllName = args.Name.Contains(&apos;,&apos;) ? args.Name.Substring(0, args.Name.IndexOf(&apos;,&apos;)) : args.Name.Replace(&quot;.dll&quot;,&quot;&quot;);
			///
			///    dllName = dllName.Replace(&quot;.&quot;, &quot;_&quot;);
			///
			///    if (dllName.EndsWith(&quot;_resources&quot;)) return null;
			///
			///    System.Resources.ResourceManager rm = new System.Resour [rest of string was truncated]&quot;;.
			/// </summary>
			const static std::wstring &getApp_xaml() const;
		};
	}
}
